//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrganizerDBEntitiesUpdated : DbContext
    {
        public OrganizerDBEntitiesUpdated()
            : base("name=OrganizerDBEntitiesUpdated")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUsersExt> AspNetUsersExts { get; set; }
        public virtual DbSet<task_table> task_table { get; set; }
        public virtual DbSet<team_table> team_table { get; set; }
    
        public virtual int spCreateTask(string title, string taskSubject, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> creatorID, Nullable<byte> taskPriority, Nullable<bool> isDeleted, Nullable<bool> isFinished, Nullable<System.DateTime> taskCreationDate)
        {
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var taskSubjectParameter = taskSubject != null ?
                new ObjectParameter("TaskSubject", taskSubject) :
                new ObjectParameter("TaskSubject", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var creatorIDParameter = creatorID.HasValue ?
                new ObjectParameter("CreatorID", creatorID) :
                new ObjectParameter("CreatorID", typeof(int));
    
            var taskPriorityParameter = taskPriority.HasValue ?
                new ObjectParameter("TaskPriority", taskPriority) :
                new ObjectParameter("TaskPriority", typeof(byte));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            var isFinishedParameter = isFinished.HasValue ?
                new ObjectParameter("IsFinished", isFinished) :
                new ObjectParameter("IsFinished", typeof(bool));
    
            var taskCreationDateParameter = taskCreationDate.HasValue ?
                new ObjectParameter("TaskCreationDate", taskCreationDate) :
                new ObjectParameter("TaskCreationDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCreateTask", titleParameter, taskSubjectParameter, startDateParameter, endDateParameter, creatorIDParameter, taskPriorityParameter, isDeletedParameter, isFinishedParameter, taskCreationDateParameter);
        }
    
        public virtual int spCreateTeam(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCreateTeam", nameParameter);
        }
    
        public virtual int spCreateUser(string newUserName, string email)
        {
            var newUserNameParameter = newUserName != null ?
                new ObjectParameter("NewUserName", newUserName) :
                new ObjectParameter("NewUserName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCreateUser", newUserNameParameter, emailParameter);
        }
    
        public virtual int spDeleteTaskByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteTaskByID", iDParameter);
        }
    
        public virtual int spDeleteTaskByTitle(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteTaskByTitle", titleParameter);
        }
    
        public virtual int spDeleteTeamByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteTeamByID", iDParameter);
        }
    
        public virtual int spDeleteTeamByName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteTeamByName", nameParameter);
        }
    
        public virtual int spDeleteTeamTask(Nullable<int> teamID, Nullable<int> taskID)
        {
            var teamIDParameter = teamID.HasValue ?
                new ObjectParameter("TeamID", teamID) :
                new ObjectParameter("TeamID", typeof(int));
    
            var taskIDParameter = taskID.HasValue ?
                new ObjectParameter("TaskID", taskID) :
                new ObjectParameter("TaskID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteTeamTask", teamIDParameter, taskIDParameter);
        }
    
        public virtual int spDeleteUser(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteUser", iDParameter);
        }
    
        public virtual int spDeleteUserTask(string userID, Nullable<int> task)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var taskParameter = task.HasValue ?
                new ObjectParameter("Task", task) :
                new ObjectParameter("Task", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteUserTask", userIDParameter, taskParameter);
        }
    
        public virtual int spDeleteUserTeam(string userID, Nullable<int> teamID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var teamIDParameter = teamID.HasValue ?
                new ObjectParameter("TeamID", teamID) :
                new ObjectParameter("TeamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteUserTeam", userIDParameter, teamIDParameter);
        }
    
        public virtual int spGetAllTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetAllTasks");
        }
    
        public virtual int spGetAllTeams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetAllTeams");
        }
    
        public virtual int spGetTaskByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetTaskByID", iDParameter);
        }
    
        public virtual int spGetTeamByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetTeamByID", iDParameter);
        }
    
        public virtual ObjectResult<spGetUserById_Result> spGetUserById(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetUserById_Result>("spGetUserById", iDParameter);
        }
    
        public virtual int spInsertTeamTask(Nullable<int> teamID, Nullable<int> taskID)
        {
            var teamIDParameter = teamID.HasValue ?
                new ObjectParameter("TeamID", teamID) :
                new ObjectParameter("TeamID", typeof(int));
    
            var taskIDParameter = taskID.HasValue ?
                new ObjectParameter("TaskID", taskID) :
                new ObjectParameter("TaskID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertTeamTask", teamIDParameter, taskIDParameter);
        }
    
        public virtual int spInsertUserTask(string userID, Nullable<int> taskID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var taskIDParameter = taskID.HasValue ?
                new ObjectParameter("TaskID", taskID) :
                new ObjectParameter("TaskID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertUserTask", userIDParameter, taskIDParameter);
        }
    
        public virtual int spInsertUserTeam(string userID, Nullable<int> teamID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var teamIDParameter = teamID.HasValue ?
                new ObjectParameter("TeamID", teamID) :
                new ObjectParameter("TeamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertUserTeam", userIDParameter, teamIDParameter);
        }
    
        public virtual int spUpdateTaskByID(Nullable<int> iD, string title, string taskSubject, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> creatorID, Nullable<byte> taskPriority, Nullable<bool> isDeleted, Nullable<bool> isFinished, Nullable<System.DateTime> taskCreationDate)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var taskSubjectParameter = taskSubject != null ?
                new ObjectParameter("TaskSubject", taskSubject) :
                new ObjectParameter("TaskSubject", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var creatorIDParameter = creatorID.HasValue ?
                new ObjectParameter("CreatorID", creatorID) :
                new ObjectParameter("CreatorID", typeof(int));
    
            var taskPriorityParameter = taskPriority.HasValue ?
                new ObjectParameter("TaskPriority", taskPriority) :
                new ObjectParameter("TaskPriority", typeof(byte));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            var isFinishedParameter = isFinished.HasValue ?
                new ObjectParameter("IsFinished", isFinished) :
                new ObjectParameter("IsFinished", typeof(bool));
    
            var taskCreationDateParameter = taskCreationDate.HasValue ?
                new ObjectParameter("TaskCreationDate", taskCreationDate) :
                new ObjectParameter("TaskCreationDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateTaskByID", iDParameter, titleParameter, taskSubjectParameter, startDateParameter, endDateParameter, creatorIDParameter, taskPriorityParameter, isDeletedParameter, isFinishedParameter, taskCreationDateParameter);
        }
    
        public virtual int spUpdateTeamByID(string name, Nullable<int> iD)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateTeamByID", nameParameter, iDParameter);
        }
    
        public virtual int spUpdateUserEmail(Nullable<int> iD, string email)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateUserEmail", iDParameter, emailParameter);
        }
    
        public virtual int spUpdateUserNameByID(Nullable<int> iD, string newUserName)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var newUserNameParameter = newUserName != null ?
                new ObjectParameter("NewUserName", newUserName) :
                new ObjectParameter("NewUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateUserNameByID", iDParameter, newUserNameParameter);
        }
    
        public virtual int spUpdateUserPhone(Nullable<int> iD, string phoneNumber)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateUserPhone", iDParameter, phoneNumberParameter);
        }
    }
}
